sonar.projectKey=sonarqube-node-demo
sonar.projectName=sonarqube-node-demo
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.tests=__tests__
sonar.exclusions=node_modules/**,coverage/**,reports/**
sonar.test.exclusions=node_modules/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
