apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-java-demo
  labels:
    app: sonarqube-java-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube-java-demo
  template:
    metadata:
      labels:
        app: sonarqube-java-demo
    spec:
      containers:
        - name: sonarqube-java-demo
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
