apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-node-demo
  labels:
    app: sonarqube-node-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube-node-demo
  template:
    metadata:
      labels:
        app: sonarqube-node-demo
    spec:
      containers:
        - name: sonarqube-node-demo
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: PORT
              value: "3000"
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
