apiVersion: v1
kind: Service
metadata:
  name: sonarqube-node-demo
  labels:
    app: sonarqube-node-demo
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: sonarqube-node-demo
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
